# Port
server:
  port: 8084

# Zipkin
spring:
  zipkin:
    enabled: true
    baseUrl: http://192.168.1.37:9411
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: Movie
  serie:
    name: Serie


# Eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Circuit Breaker
resilience4j:
  retry:
    instances:
      movie:
        maxAttempts: 3
        waitDuration: 1000
        retryException[0]: feign.feignException$InternalServerError
  circuitbreaker:
    instances:
      movie:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true
    
# Actuator
# management:
#   endpoints:
#     web:
#       exposure:
#         include: *
#   info:
#     end:
#       enabled: true
#   health:
#     circuitbreakers:
#       enabled: true
