server:
  port: 8080
  

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: lb://MOVIE-SERVICE #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
          filters:
            - AddResponseHeader=movie-response-header, RESPONSE header added to movie-service
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: lb://CATALOG-SERVICE #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalogs/**
          filters:
            - AddRequestHeader=catalog-request-header, custom REQUEST header to movie-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka