# Port
server:
  port: 8080
  
# Spring
spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      discovery:
        locator:
          enabled: true
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: lb://MOVIE-SERVICE #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
        - id: catalogRoute #Identificando la ruta del service de producto
          uri: lb://CATALOG-SERVICE #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/catalogs/**
  zipkin:
    enabled: true
    baseUrl: http://192.168.1.37:9411
    
# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka