# Port
server:
  port: 8095

# Spring
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: finalBackSerie
      port: 27017
      host: mongodb
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: Movie

# Eureka
eureka:
  # instance:
  #   hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka